### PR TITLE
Minor updates and fixes to jupyter notebooks 1 - 4

### PR DESCRIPTION
**Pull request by adiezsanchez**
Hi, I am just following this amazing resource that you have created and have included and fixed some things that were not working for me. I encountered one problem with the aicsimageio reader, apparently it is built using a pydantic dependency that breaks the reader. Pydantic has been updated to V2, so I needed to downgrade manually to pydantic 1.10.11 to make the aicsimageio module work.

This is my first pull request, so please ignore it if not done correctly or properly :). Also some feedback on how should I do it is greatly appreciated.

Best,

Alberto

### CODE REVIEW

**Comment by guiwitz** [comment]
Thanks a lot for the PR @adiezsanchez ! How did you setup your environment? Did you use the ```installation/environment_minimal.yml``` file? I see now that the Python version is really old there :scream: I have to create an environment to review your changes, so I'm just pondering on updating.

**Comment by guiwitz** [comment]
Ok I just tried and conda doesn't even find python 3.7 :laughing: Just let me know what you used and I'll try to update the installation file later.

**Comment by adiezsanchez** [comment]
Hi @guiwitz , I just recreated the environment from the .yml file that was within the binder folder (not the one in installation) using mamba. Here's the list of packages it contained. It was all working wonders until I had to import the aicsimagereader package used in chapter4 (Image import).

packages in environment at C:\Users\albertds\mambaforge\envs\biapy:
Name                    Version                   Build  Channel
aicsimageio               4.7.0                    pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py37hcc03f2d_2    conda-forge
asciitree                 0.3.3                    pypi_0    pypi
attrs                     23.1.0             pyh71513ae_1    conda-forge
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.4               hdccc3a2_0    conda-forge
bqplot                    0.12.40            pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                hcfcfb64_9    conda-forge
brotli-bin                1.0.9                hcfcfb64_9    conda-forge
brotli-python             1.0.9            py37hf2a7229_7    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-blosc2                  2.10.0               h183a6f4_0    conda-forge
ca-certificates           2023.5.7             h56e8100_0    conda-forge
cachey                    0.2.1                    pypi_0    pypi
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37ha95fbe2_1    conda-forge
cfitsio                   4.0.0                hd67004f_0    conda-forge
charls                    2.3.4                h39d44d4_0    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
click                     8.1.4                    pypi_0    pypi
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0           py37hcc03f2d_0    conda-forge
dask-core                 2022.2.0           pyhd8ed1ab_0    conda-forge
debugpy                   1.6.3            py37hf2a7229_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
dnspython                 2.3.0                    pypi_0    pypi
docstring-parser          0.15                     pypi_0    pypi
docutils                  0.19                     pypi_0    pypi
elementpath               4.1.4                    pypi_0    pypi
email-validator           2.0.0.post2              pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.2              pyhd8ed1ab_0    conda-forge
fasteners                 0.18                     pypi_0    pypi
flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.38.0           py37h51bd9d9_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
freetype-py               2.4.0                    pypi_0    pypi
fsspec                    2023.1.0           pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
giflib                    5.2.1                h64bf75a_3    conda-forge
glib                      2.76.4               h12be248_0    conda-forge
glib-tools                2.76.4               h12be248_0    conda-forge
gst-plugins-base          1.22.4               h001b923_1    conda-forge
gstreamer                 1.22.4               hb4038d2_1    conda-forge
heapdict                  1.0.1                    pypi_0    pypi
hsluv                     5.0.3                    pypi_0    pypi
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2021.11.20       py37hfea8715_2    conda-forge
imageio                   2.31.1             pyh24c5eb1_0    conda-forge
imagesize                 1.4.1                    pypi_0    pypi
imglyb                    2.1.0              pyha21a80b_0    conda-forge
importlib-metadata        4.11.4           py37h03978a9_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       6.0.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2023.1.0         h57928b3_46319    conda-forge
ipydatawidgets            4.3.2              pyhc268e32_0    conda-forge
ipykernel                 6.16.2             pyh025b116_0    conda-forge
ipython                   7.33.0           py37h03978a9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipyvolume                 0.6.3              pyhd8ed1ab_0    conda-forge
ipyvue                    1.9.1              pyhd8ed1ab_0    conda-forge
ipyvuetify                1.8.10             pyhd8ed1ab_0    conda-forge
ipywebrtc                 0.6.0              pyhd8ed1ab_0    conda-forge
ipywidgets                8.0.7              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jgo                       1.0.5              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
jpype1                    1.4.0            py37h8c56517_0    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py37h03978a9_7    conda-forge
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_console           6.5.1              pyhd8ed1ab_0    conda-forge
jupyter_contrib_core      0.4.0              pyhd8ed1ab_0    conda-forge
jupyter_contrib_nbextensions 0.7.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py37h03978a9_0    conda-forge
jupyter_highlight_selected_word 0.2.0           py37h03978a9_1005    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.6.1              pyhd8ed1ab_0    conda-forge
jupyter_server            1.23.4             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.8              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kiwisolver                1.4.4            py37h8c56517_0    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
labeling                  0.1.12             pyhd8ed1ab_1    conda-forge
lcms2                     2.14                 h90d422f_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libaec                    1.0.6                h63175ca_1    conda-forge
libblas                   3.9.0              17_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_9    conda-forge
libbrotlidec              1.0.9                hcfcfb64_9    conda-forge
libbrotlienc              1.0.9                hcfcfb64_9    conda-forge
libcblas                  3.9.0              17_win64_mkl    conda-forge
libclang                  15.0.7          default_h77d9078_2    conda-forge
libclang13                15.0.7          default_h77d9078_2    conda-forge
libcurl                   8.1.2                h68f0423_0    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.76.4               he8f3873_0    conda-forge
libhwloc                  2.9.1           nocuda_h15da153_6    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              17_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.4.0                hc4061b1_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.3.1                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.11.4               hc3477c8_0    conda-forge
libxslt                   1.1.37               h6070c61_1    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
looseversion              1.3.0                    pypi_0    pypi
lxml                      4.9.1            py37hcc03f2d_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
magicgui                  0.6.1                    pypi_0    pypi
markupsafe                2.1.1            py37hcc03f2d_1    conda-forge
matplotlib                3.5.3            py37h03978a9_2    conda-forge
matplotlib-base           3.5.3            py37hbaab90a_2    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
maven                     3.9.3                h57928b3_0    conda-forge
mistune                   3.0.0              pyhd8ed1ab_0    conda-forge
mizani                    0.7.3              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
mrc                       0.3.1                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy-extensions           1.0.0                    pypi_0    pypi
napari                    0.4.14                   pypi_0    pypi
napari-console            0.0.7                    pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-svg                0.1.10                   pypi_0    pypi
nbclassic                 1.0.0              pyhb4ecaf3_1    conda-forge
nbclient                  0.7.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.6.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.6.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.6.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
notebook                  6.5.4              pyha770c72_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
npe2                      0.2.1                    pypi_0    pypi
numcodecs                 0.10.2                   pypi_0    pypi
numpy                     1.21.6           py37h2830a78_0    conda-forge
numpydoc                  1.5.0                    pypi_0    pypi
ome-types                 0.3.4                    pypi_0    pypi
openjdk                   8.0.332              h57928b3_0    conda-forge
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   3.1.1                hcfcfb64_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
palettable                3.3.3              pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py37h9386db6_0    conda-forge
pandoc                    3.1.3                h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.4.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py37h42a8222_2    conda-forge
pint                      0.18                     pypi_0    pypi
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
plotnine                  0.8.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psutil                    5.9.3            py37h51bd9d9_0    conda-forge
psygnal                   0.9.1                    pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.11                  pypi_0    pypi
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pyimagej                  1.2.1            py37h03978a9_0    conda-forge
pyjnius                   1.2.0            py37hf78f419_0    conda-forge
pyopengl                  3.1.7                    pypi_0    pypi
pyparsing                 3.1.0              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py37h15e4627_1    conda-forge
pyqt5-sip                 12.11.0          py37h7f67f24_1    conda-forge
pyrsistent                0.18.1           py37hcc03f2d_1    conda-forge
pysocks                   1.7.1            py37h03978a9_5    conda-forge
python                    3.7.12          h900ac77_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.17.1             pyhd8ed1ab_0    conda-forge
python_abi                3.7                     3_cp37m    conda-forge
pythreejs                 2.4.2              pyh1d7be83_0    conda-forge
pytomlpp                  1.0.13                   pypi_0    pypi
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py37h3a130e4_1    conda-forge
pywin32                   303              py37hcc03f2d_0    conda-forge
pywinpty                  2.0.8            py37h7f67f24_0    conda-forge
pyyaml                    6.0              py37hcc03f2d_4    conda-forge
pyzmq                     24.0.1           py37h7347f05_0    conda-forge
qt-main                   5.15.8               h720456b_6    conda-forge
qtconsole                 5.4.3              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.3              pyha770c72_0    conda-forge
qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
scikit-image              0.19.3           py37h3182a2c_1    conda-forge
scipy                     1.7.3            py37hb6553fb_0    conda-forge
scyjava                   1.9.1              pyhd8ed1ab_0    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.2              pyh08f2357_0    conda-forge
setuptools                59.8.0           py37h03978a9_1    conda-forge
sip                       6.7.2            py37h7f67f24_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               hfb803bf_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    5.3.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.42.0               hcfcfb64_0    conda-forge
statsmodels               0.13.2           py37h3a130e4_0    conda-forge
superqt                   0.4.1                    pypi_0    pypi
tbb                       2021.9.0             h91493d7_0    conda-forge
terminado                 0.17.0             pyh08f2357_0    conda-forge
tifffile                  2021.11.2          pyhd8ed1ab_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py37hcc03f2d_0    conda-forge
tqdm                      4.65.0                   pypi_0    pypi
trackpy                   0.6.1                    pypi_0    pypi
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
typer                     0.9.0                    pypi_0    pypi
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py37hcc03f2d_1    conda-forge
urllib3                   2.0.3              pyhd8ed1ab_1    conda-forge
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hfdfe4a8_17    conda-forge
vispy                     0.13.0                   pypi_0    pypi
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.6.1              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.8              pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.15.0                   pypi_0    pypi
xarray                    0.20.2             pyhd8ed1ab_0    conda-forge
xlrd                      2.0.1                    pypi_0    pypi
xmlschema                 2.3.1                    pypi_0    pypi
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zarr                      2.12.0                   pypi_0    pypi
zeromq                    4.3.4                h0e60522_1    conda-forge
zfp                       0.5.5                h0e60522_8    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib-ng                   2.0.7                hcfcfb64_0    conda-forge
zstd                      1.5.2                h12be248_7    conda-forge

**Comment by guiwitz** [comment]
Ok so I checked the PR. Great fixes and additions, many thanks! I just removed most of the .gitignore for the Data folder which as the repo is not supposed to contain that folder. Also FYI you can just add something like ```Data/*``` to remove anything inside a folder, no need to list all files.

I ran the notebooks with an updated environment using Python 3.10 (I'll push an updated env file later) and more recent versions of the packages but it looks like nothing else is broken at this point. I would recommend to create a new environment with the the updated file to check the remaining notebooks.

**Comment by adiezsanchez** [comment]
Thanks for checking it and creating an updated environment. I see, so just using a wildcard you can get rid of that long list of folders in the .gitignore. It was what VSCode automatically generated when I ignored the Data folder. I have not tried it, but maybe for the download_data.py one could just change this piece of code (and the subsequent ones):

if not os.path.exists('Data/'):
    os.makedirs('Data/')

into using a relative filepath "../Data/" so the folder and the unzipping already occurs outside of the neubias_academy_biapy

**Pull request merged**
